# -*- coding: utf-8 -*-
"""checkpointPandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yu3bEOm_-BBeo83us2igPz-iwoLVM-sr
"""

dict2= {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 20, 14.5,15,7,17,8, 19,12],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

import pandas as pd 
data=pd.DataFrame(dict2)
data.to_csv("data.csv",index=False) #question7
new_data=pd.read_csv("data.csv")
new_data.head() #question1

new_data.dropna(inplace=True) #question2

new_data

df=new_data[["name","score"]] #question3
print(df)

dict3={'name' : ["Suresh"], 'score':[15.5], 'attempts': [1], 'qualify': ["yes"]} #question4
import pandas as pd
data2= pd.DataFrame(dict3)
new_data5=pd.concat([new_data,data2])
print(new_data5)

new_data.drop("attempts", axis=1) #question5

#question6
success=[]
for i in  new_data['score']:
  if i<10:
    i=0
    success.append(i)
  else:
    i=1
    success.append(i)
print(success)

new_data['Success']=success

new_data